# Encoding: UTF-8
# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms}
  s.version           = %q{1.0.4}
  s.description       = %q{A Ruby on Rails CMS that supports Rails 3. It's easy to extend and sticks to 'the Rails way' where possible.}
  s.date              = %q{2011-08-21}
  s.summary           = %q{A Ruby on Rails CMS that supports Rails 3}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.rubyforge_project = %q{refinerycms}
  s.authors           = ['Resolve Digital', 'Philip Arndt', 'David Jones', 'Steven Heidel', 'Uģis Ozols']
  s.license           = %q{MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w(refinerycms alpha)

  # Bundler
  s.add_dependency    'bundler',                    '~> 1.0.10'
  s.add_dependency    'thor'
  s.add_dependency    'rails',                      '~> 3.0.7.rc2'

  s.add_development_dependency  'cucumber'
  s.add_development_dependency  'aruba'
  s.add_development_dependency  'rspec',            '>= 2.0.0'

  # Refinery CMS
  s.add_dependency    'refinerycms-authentication', '= 1.0.4'
  s.add_dependency    'refinerycms-base',           '= 1.0.4'
  s.add_dependency    'refinerycms-core',           '= 1.0.4'
  s.add_dependency    'refinerycms-dashboard',      '= 1.0.4'
  s.add_dependency    'refinerycms-images',         '= 1.0.4'
  s.add_dependency    'refinerycms-pages',          '= 1.0.4'
  s.add_dependency    'refinerycms-resources',      '= 1.0.4'
  s.add_dependency    'refinerycms-settings',       '= 1.0.4'

  s.files             = [
    '.gitignore',
    '.rspec',
    'Gemfile',
    'Gemfile',
    'Gemfile.lock',
    'Rakefile',
    'app',
    'app/views',
    'app/views/sitemap',
    'app/views/sitemap/index.xml.builder',
    'autotest',
    'autotest/autotest.rb.backup',
    'autotest/discover.rb.backup',
    'bin',
    'bin/alpha',
    'bin/refinerycms',
    'changelog.md',
    'changelog.md',
    'config',
    'config/app',
    'config/app/development.rb',
    'config/app/production.rb',
    'config/app/test.rb',
    'config/app.rb',
    'config/app.rb.sample',
    'config/cucumber.yml',
    'config/environments',
    'config/environments/development.rb',
    'config/environments/production.rb',
    'config/environments/test.rb',
    'config/mongoid.yml',
    'config/mongoid.yml.sample',
    'config/routes.rb',
    'config/settings.rb',
    'config.ru',
    'features',
    'features/support',
    'features/support/paths.rb',
    'lib',
    'lib/alpha',
    'lib/alpha/cli.rb',
    'lib/alpha/templates',
    'lib/alpha/templates/bootstrap.rb',
    'lib/alpha/templates/datetime_initializer.rb',
    'lib/alpha/templates/delayed_job_initializer.rb',
    'lib/alpha/templates/evergreen.rb',
    'lib/alpha/templates/finalize.rb',
    'lib/alpha/templates/gemfile.rb',
    'lib/alpha/templates/gemfile_setup.rb',
    'lib/alpha/templates/generators_initializer.rb',
    'lib/alpha/templates/gitignore.rb',
    'lib/alpha/templates/haml.rb',
    'lib/alpha/templates/hoptoad_initializer.rb',
    'lib/alpha/templates/mongoid.rb',
    'lib/alpha/templates/newrelic.rb',
    'lib/alpha/templates/rails_clean.rb',
    'lib/alpha/templates/refinerycms.rb',
    'lib/alpha/templates/sass.rb',
    'lib/alpha/templates/testing.rb',
    'lib/alpha/version.rb',
    'lib/load_path_analyzer.rb',
    'lib/refinery.rb',
    'lib/refinerycms',
    'lib/refinerycms/all.rb',
    'lib/refinerycms.rb',
    'license.md',
    'license.md',
    'public',
    'public/javascripts',
    'public/javascripts/translations.js',
    'readme.md',
    'readme.md',
    'refinerycms.gemspec',
    'spec',
    'spec/rcov.opts',
    'spec/spec_helper.rb',
    'spec/support',
    'spec/support/refinery',
    'spec/support/refinery/controller_macros.rb'
  ]
end
