# DO NOT EDIT THIS FILE DIRECTLY! Instead, use lib/gemspec.rb to generate it.

Gem::Specification.new do |s|
  s.name              = %q{refinerycms}
  s.version           = %q{0.9.9.3}
  s.description       = %q{A Ruby on Rails CMS that supports Rails 3. It's easy to extend and sticks to 'the Rails way' where possible.}
  s.date              = %q{2011-02-18}
  s.summary           = %q{A Ruby on Rails CMS that supports Rails 3}
  s.email             = %q{info@refinerycms.com}
  s.homepage          = %q{http://refinerycms.com}
  s.rubyforge_project = %q{refinerycms}
  s.authors           = ['Resolve Digital', 'Philip Arndt', 'David Jones', 'Steven Heidel']
  s.license           = %q{MIT}
  s.require_paths     = %w(lib)
  s.executables       = %w()

  # Bundler
  s.add_dependency    'bundler',                    '~> 1.0.10'

  # Refinery CMS
  s.add_dependency    'refinerycms-authentication', '~> 0.9.9.3'
  s.add_dependency    'refinerycms-base',           '~> 0.9.9.3'
  s.add_dependency    'refinerycms-core',           '~> 0.9.9.3'
  s.add_dependency    'refinerycms-dashboard',      '~> 0.9.9.3'
  s.add_dependency    'refinerycms-images',         '~> 0.9.9.3'
  s.add_dependency    'refinerycms-pages',          '~> 0.9.9.3'
  s.add_dependency    'refinerycms-resources',      '~> 0.9.9.3'
  s.add_dependency    'refinerycms-settings',       '~> 0.9.9.3'

  s.files             = [
    'gemspec.rb',
    'refinery.rb',
    'refinerycms.rb'
  ]
end
