source "http://www.rubygems.org"

gemspec

gem 'refinerycms-base', :path => '../base'
gem 'refinerycms-settings', :path => '../settings'
gem 'refinerycms-generators', :path => '../../refinerycms-generators'

gem 'mongoid', :git => 'git://github.com/mongoid/mongoid.git'
gem 'bson_ext', '>= 1.2.1'
gem 'mongoid_slug', :require => 'mongoid/slug'
gem 'mongoid_nested_set', :git => 'git://github.com/activefx/mongoid_nested_set.git'
gem 'mongoid_search', :git => 'git://github.com/activefx/mongoid_search_relevant.git'

